### ISSUE TITLE
Move Commands

### ISSUE THREAD

**Issue by wizzymore** [wizzymore/OregonCore#1]
- [x] event
- [x] gobject
  - [x] add
  - [x] delete
  - [x] target
  - [x] turn
  - [x] move
  - [x] near
  - [x] activate
  - [x] addtemp
- [x] honor
- [x] group
- [x] wp
- [ ] loadpath
- [x] titles
- [x] list
- [x] lookup
- [x] pdump
  - [x] load
  - [x] write
- [x] guild
- [x] reset
- [x] cast
- [x] pet
  - [x] create
  - [x] learn
  - [x] unlearn
  - [x] tp
- [x] account
- [x] gm
- [x] ticket
- [x] npc
- [x] go
- [x] learn
- [x] modify
- [x] debug
- [x] tele
- [x] character
- [x] quest
  - [x] add
  - [x] remove
  - [x] complete
- [x] reload
- [x] instance
  - [x]  listbinds
  - [x]  unbind
  - [x]  stats
  - [x]  savedata
- [x] server
  - [x] shutdown
  - [x] set
  - [x] restart
  - [x] motd
  - [x] info
  - [x] exit
  - [x] corpses
  - [x] logmask
  - [x] difftime
  - [x] idlerestart
  - [x] idleshutdown
- [x] cheat
  - [x] god
  - [x] power
  - [x] cast
  - [x] casttime
  - [x] cooldown
  - [x] waterwalk
  - [x] explore
- [x] aura
- [x] unaura
- [x] nameannounce
- [x] gmnameannounce
- [x] announce
- [x] gmannounce
- [x] notify
- [x] gmnotify
- [x] appear
- [x] summon
- [x] groupsummon
- [x] commands
- [x] demorph
- [x] die
- [x] revive
- [x] dismount
- [x] gps
- [x] guid
- [x] help
- [x] itemmove
- [x] cooldown
- [x] unlearn
- [x] distance
- [x] recall
- [x] save
- [x] saveall
- [x] kick
- [x] ban
- [x] unban
- [x] baninfo
- [x] banlist
- [x] start
- [x] allowmove
- [x] linkgrave
- [x] neargrave
- [x] hover
- [x] levelup
- [x] showarea
- [x] hidearea
- [x] additem
- [x] additemset
- [x] bank
- [x] wchange
- [x] maxskill
- [x] setskill
- [x] whispers
- [x] pinfo
- [x] send ( new command structure )
-- items
-- mail
-- message
-- money
- [x] respawn
- [x] mute
- [x] unmute
- [x] movegens
- [x] cometome
- [x] damage
- [x] combatstop
- [x] ahbotoptions
- [x] flusharenapoints
- [x] playall
- [x] repairitems
- [x] freeze
- [x] unfreeze
- [x] listfreeze
- [x] possess
- [x] unpossess
- [x] bindsight
- [x] unbindsight
- [x] raf ( refer a friend )

**Comment by yuanf225** [comment]
Great

**Comment by wizzymore** [comment]
This was merged in Talamortis core
